/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    I18nDemo: typeof import('./src/components/I18nDemo.vue')['default']
    ThemeDemo: typeof import('./src/components/ThemeDemo.vue')['default']
  }
}
