/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Buttons: typeof import('./../components/buttons.vue')['default']
    Colors: typeof import('./../components/colors.vue')['default']
    I18nDemo: typeof import('./../components/I18nDemo.vue')['default']
    Icon: typeof import('./../components/icon.vue')['default']
    ThemeDemo: typeof import('./../components/ThemeDemo.vue')['default']
  }
}
