/**
 * 常量配置文件
 * 包含版本信息、Element Plus 映射表等常量
 */

// ==================== 版本信息 ====================
export const VERSION = '1.0.38'
export const AUTHOR = 'chenyu'
export const DESCRIPTION = '自定义组件库，提供自定义组件和工具函数'

// ==================== Element Plus 组件映射表 ====================
// m- 前缀到 el- 前缀的映射
export const ELEMENT_PLUS_MAPPING = {
  'm-input': 'ElInput',
  'm-button': 'ElButton',
  'm-card': 'ElCard',
  'm-form': 'ElForm',
  'm-form-item': 'ElFormItem',
  'm-select': 'ElSelect',
  'm-option': 'ElOption',
  'm-date-picker': 'ElDatePicker',
  'm-time-picker': 'ElTimePicker',
  'm-table': 'ElTable',
  'm-table-column': 'ElTableColumn',
  'm-pagination': 'ElPagination',
  'm-dialog': 'ElDialog',
  'm-drawer': 'ElDrawer',
  'm-popover': 'ElPopover',
  'm-tooltip': 'ElTooltip',
  'm-dropdown': 'ElDropdown',
  'm-dropdown-menu': 'ElDropdownMenu',
  'm-dropdown-item': 'ElDropdownItem',
  'm-menu': 'ElMenu',
  'm-menu-item': 'ElMenuItem',
  'm-submenu': 'ElSubMenu',
  'm-tabs': 'ElTabs',
  'm-tab-pane': 'ElTabPane',
  'm-steps': 'ElSteps',
  'm-step': 'ElStep',
  'm-breadcrumb': 'ElBreadcrumb',
  'm-breadcrumb-item': 'ElBreadcrumbItem',
  'm-alert': 'ElAlert',
  'm-notification': 'ElNotification',
  'm-message': 'ElMessage',
  'm-message-box': 'ElMessageBox',
  'm-loading': 'ElLoading',
  'm-infinite-scroll': 'ElInfiniteScroll',
  'm-image': 'ElImage',
  'm-avatar': 'ElAvatar',
  'm-badge': 'ElBadge',
  'm-tag': 'ElTag',
  'm-progress': 'ElProgress',
  'm-skeleton': 'ElSkeleton',
  'm-empty': 'ElEmpty',
  'm-descriptions': 'ElDescriptions',
  'm-descriptions-item': 'ElDescriptionsItem',
  'm-result': 'ElResult',
  'm-statistic': 'ElStatistic',
  'm-timeline': 'ElTimeline',
  'm-timeline-item': 'ElTimelineItem',
  'm-calendar': 'ElCalendar',
  'm-carousel': 'ElCarousel',
  'm-carousel-item': 'ElCarouselItem',
  'm-collapse': 'ElCollapse',
  'm-collapse-item': 'ElCollapseItem',
  'm-divider': 'ElDivider',
  'm-link': 'ElLink',
  'm-text': 'ElText',
  'm-space': 'ElSpace',
  'm-affix': 'ElAffix',
  'm-backtop': 'ElBacktop',
  'm-page-header': 'ElPageHeader',
  'm-radio': 'ElRadio',
  'm-radio-group': 'ElRadioGroup',
  'm-radio-button': 'ElRadioButton',
  'm-checkbox': 'ElCheckbox',
  'm-checkbox-group': 'ElCheckboxGroup',
  'm-checkbox-button': 'ElCheckboxButton',
  'm-switch': 'ElSwitch',
  'm-slider': 'ElSlider',
  'm-rate': 'ElRate',
  'm-color-picker': 'ElColorPicker',
  'm-transfer': 'ElTransfer',
  'm-tree': 'ElTree',
  'm-tree-select': 'ElTreeSelect',
  'm-cascader': 'ElCascader',
  'm-upload': 'ElUpload',
  'm-upload-dragger': 'ElUploadDragger',
  'm-upload-list': 'ElUploadList'
}
