name: Gitee Pages

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build demo
      run: npm run build:demo
      
    - name: Deploy to Gitee Pages
      uses: yanglbme/gitee-pages-action@main
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      with:
        gitee-username: ${{ secrets.GITEE_USERNAME }}
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        gitee-repo: ${{ secrets.GITEE_REPO }}
        branch: master
        directory: dist-demo
